## Operaciones basicas

In [1]:
import numpy as np

In [2]:
ar1 = np.arange(5)

In [3]:
print(ar1*10)

[ 0 10 20 30 40]


In [4]:
print(ar1-1)

[-1  0  1  2  3]


In [5]:
ar1**2

array([ 0,  1,  4,  9, 16])

In [6]:
ar2=np.arange(0,10,2)
ar2

array([0, 2, 4, 6, 8])

In [7]:
(ar1+ar2)**ar1

array([    1,     3,    36,   729, 20736])

In [8]:
a = np.arange(10000)
%timeit a + 1  

l = range(10000)
%timeit [i+1 for i in l] 

3.26 µs ± 64.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
552 µs ± 48.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Comparación de arreglos

In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = b[::].copy()
a == b


array([False,  True, False,  True])

In [10]:
a > b

array([False, False,  True, False])

In [11]:
#Operación lógica
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
np.logical_or(a, b)


array([ True,  True,  True, False])

In [12]:
np.logical_and(a, b)

array([ True, False, False, False])

## Sums

In [13]:
s = np.arange(0,10)
s.sum() == np.sum(s)


True

In [14]:
ar3x3 = s[0:9].reshape(3,3)
ar3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
ar3x3.sum(axis=0) #suma por columna

array([ 9, 12, 15])

In [16]:
ar3x3.sum(axis=1) #suma por fila

array([ 3, 12, 21])

In [17]:
ar3x3[:,1].sum() #suma de la segunda columna

12

In [18]:
ar3x3[0,:].sum() #Suma primera fila

3

## Sort

In [24]:
ar1 = np.array([[1,4,6,7],[3,3,4,5],[1,5,2,4]])
ar1

array([[1, 4, 6, 7],
       [3, 3, 4, 5],
       [1, 5, 2, 4]])

In [25]:
ar1.sort(axis=0)
ar1

array([[1, 3, 2, 4],
       [1, 4, 4, 5],
       [3, 5, 6, 7]])

In [27]:
ar1.sort(axis=1)
ar1

array([[1, 2, 3, 4],
       [1, 4, 4, 5],
       [3, 5, 6, 7]])