## Casting

In [1]:
import numpy as np

In [2]:
ar = np.array([12,43,56,55]) 
ar

array([12, 43, 56, 55])

In [3]:
ar.dtype

dtype('int64')

In [4]:
ar2 = ar+.1
print(ar2.dtype)
ar2

float64


array([12.1, 43.1, 56.1, 55.1])

In [5]:
ar[0]=2.7 # Asigna la parte entera, truncando la parte decimal
ar

array([ 2, 43, 56, 55])

In [6]:
ar2 = ar2.astype('int32') #Convertir a entero 32bit en numpy, de forma implicita
ar2

array([12, 43, 56, 55], dtype=int32)

## Fichero

In [7]:
ar_ex = np.zeros(27).reshape(9,3)

#Guardar fichero
np.savetxt(fname='ficheroex.csv',X=ar_ex,delimiter=';',header='a;b;c',fmt='%d') 

In [8]:
!head ficheroex.csv -n 3

# a;b;c
0;0;0
0;0;0


In [9]:
ar_ex2 = np.loadtxt(fname='ficheroex.csv',delimiter=';') 
ar_ex2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
!rm ficheroex.csv

## Matriz transpuesta

In [12]:
A = np.arange(0,9,1).reshape(3,3)

In [13]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
At=A.T ## Convertir a tranpuesta
At

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [16]:
A[2,:]

array([6, 7, 8])

In [19]:
At[:,2]

array([6, 7, 8])

In [20]:
A[2,:] == At[:,2] #Columna es igual la fila transpuesta

array([ True,  True,  True])

In [21]:
np.equal(A,At) #Diagonal es igua

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [24]:
np.swapaxes?
