## Casting

In [4]:
import numpy as np

In [6]:
ar = np.array([12,43,56,55]) 
ar

array([12, 43, 56, 55])

In [7]:
ar.dtype

dtype('int64')

In [14]:
ar2 = ar+.1
print(ar2.dtype)
ar2

float64


array([ 2.1, 43.1, 56.1, 55.1])

In [12]:
ar[0]=2.7 # Asigna la parte entera, truncando la parte decimal
ar

array([ 2, 43, 56, 55])

In [20]:
ar2 = ar2.astype('int32') #Convertir a entero 32bit en numpy, de forma implicita
ar2

array([ 2, 43, 56, 55], dtype=int32)

## Fichero

In [37]:
ar_ex = np.zeros(27).reshape(9,3)

#Guardar fichero
np.savetxt(fname='ficheroex.csv',X=ar_ex,delimiter=';',header='a;b;c',fmt='%d') 

In [41]:
!head ficheroex.csv -n 3

# a;b;c
0;0;0
0;0;0


In [45]:
ar_ex2 = np.loadtxt(fname='ficheroex.csv',delimiter=';') 
ar_ex2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
!rm ficheroex.csv