# Statistics functions

In [3]:
import numpy as np

In [36]:
ar = np.random.randint(0,100,size=100)
ar

array([27, 93, 41,  2, 42, 30, 95, 23, 71,  7, 15, 77, 64, 17, 35, 27, 45,
        1, 79, 66, 31, 77,  4, 80, 94, 68, 60, 34, 36, 99, 18,  2, 54, 38,
       29, 59, 26, 55, 87, 12,  8, 81,  8, 24, 74, 18, 36, 93, 74, 91, 58,
       95, 39, 96, 52, 88, 43, 46, 24, 31, 85, 39, 45, 30, 18, 32, 58, 14,
       58,  9, 10, 79, 93, 80, 17, 89, 43, 56, 23, 14, 76, 81, 35, 25, 70,
       35, 70,  6, 70, 44,  3, 29, 99, 12,  3, 53, 97, 20, 62, 10])

In [37]:
np.amin(ar) #Devuelve el mínimo de una matriz o el mínimo a lo largo de un eje

1

In [38]:
np.amax(ar) #Devuelve el máximo de una matriz o el máximo a lo largo de un eje.

99

In [40]:
np.ptp(ar) #Rango de valores (máximo - mínimo) a lo largo de un eje.

98

In [44]:
np.percentile(ar,10) #Calcule el percentil q-ésimo de los datos a lo largo del eje especificado.

8.9

In [49]:
np.quantile(ar,q=[0.25,0.50]) #Calcule el q-ésimo cuantil de los datos a lo largo del eje especificado.

array([23. , 42.5])

## Promedia y varianza

In [51]:
np.median(ar) #Mediana

42.5

In [52]:
np.average(ar) #promedio

46.91

In [53]:
np.mean(ar) #Media

46.91

In [54]:
np.std(ar) #Desviación estándar

29.51308015101101

In [56]:
np.var(ar) #Varianza

871.0219000000001

## Correlación

In [58]:
ar2 = np.random.randint(0,100, size=100)
ar2

array([42, 93, 29, 64, 42, 74, 13, 43, 57, 25, 54, 25, 79, 87, 53, 88, 18,
       82, 17, 50,  0,  0,  1, 22, 74, 59, 82, 52,  5, 40, 51, 65, 47, 84,
       70, 29, 68, 37, 93, 54, 64, 35, 70, 34, 65, 51, 10, 75, 31, 62, 15,
       29, 20, 19, 46, 37, 52, 43,  6,  5, 69, 41, 25, 84,  0, 50, 89, 80,
       56, 49, 19, 59, 48, 34, 97, 58, 59, 36, 84, 82, 20, 58, 10, 23, 51,
       92,  9, 73, 91, 52, 30, 54, 69, 63, 99, 94, 92, 41, 16,  2])

In [62]:
np.corrcoef(ar,ar2) #Devuelve los coeficientes de correlación producto-momento de Pearson.

array([[ 1.        , -0.02782389],
       [-0.02782389,  1.        ]])

In [64]:
np.correlate(ar,ar2) #Correlación cruzada de dos secuencias unidimensionales.

array([227395])

## Histogramas

In [68]:
np.histogram(ar2) #Genera el histograma de un conjunto de datos

(array([ 9,  9, 10,  8, 11, 19,  9,  7, 10,  8]),
 array([ 0. ,  9.9, 19.8, 29.7, 39.6, 49.5, 59.4, 69.3, 79.2, 89.1, 99. ]))

In [73]:
bins = np.bincount(ar2) #Determina la cuenta de apariciones de un conjunto dado
bins


array([3, 1, 1, 0, 0, 2, 1, 0, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 1, 2, 2, 0,
       1, 1, 0, 3, 0, 0, 0, 3, 1, 1, 0, 0, 2, 1, 1, 2, 0, 0, 1, 2, 2, 2,
       0, 0, 1, 1, 1, 1, 2, 3, 3, 1, 3, 0, 1, 1, 2, 3, 0, 0, 1, 1, 2, 2,
       0, 0, 1, 2, 2, 0, 0, 1, 2, 1, 0, 0, 0, 1, 1, 0, 3, 0, 3, 0, 0, 1,
       1, 1, 0, 1, 2, 2, 1, 0, 0, 1, 0, 1])

3