In [1]:
import pandas as pd
import numpy as np

In [2]:
#concatenate numpy

In [3]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
#concatenate pandas

In [7]:
ser1 = pd.Series([1,2,3],index=['A','B','C'])
ser1

A    1
B    2
C    3
dtype: int64

In [8]:
ser3 = pd.Series([4,5,6],index=['D','E','F'])
ser3

D    4
E    5
F    6
dtype: int64

In [9]:
pd.concat([ser1,ser3]) #axis 0 default

A    1
B    2
C    3
D    4
E    5
F    6
dtype: int64

In [10]:
pd.concat([ser1,ser3],axis=1) #add new series

0    1
A  1.0  NaN
B  2.0  NaN
C  3.0  NaN
D  NaN  4.0
E  NaN  5.0
F  NaN  6.0

In [11]:
df1 = pd.DataFrame(np.random.randn(4,3),columns=['A','B','C'])
df2 = pd.DataFrame(np.random.randn(4,3),columns=['C','E','F'])

In [12]:
df1

A         B         C
0 -0.527470 -0.611288  0.609666
1 -1.330374 -1.282318 -1.551537
2 -1.098868  0.456488  0.352204
3  1.786392  0.991445 -0.485267

In [13]:
df2

C         E         F
0 -1.692135  0.176689 -0.327256
1  0.351587  0.015693  0.887437
2  1.467077 -0.987346 -1.587642
3  0.999575 -0.965228  0.100990

In [14]:
pd.concat([df1,df2])

A         B         C         E         F
0 -0.527470 -0.611288  0.609666       NaN       NaN
1 -1.330374 -1.282318 -1.551537       NaN       NaN
2 -1.098868  0.456488  0.352204       NaN       NaN
3  1.786392  0.991445 -0.485267       NaN       NaN
0       NaN       NaN -1.692135  0.176689 -0.327256
1       NaN       NaN  0.351587  0.015693  0.887437
2       NaN       NaN  1.467077 -0.987346 -1.587642
3       NaN       NaN  0.999575 -0.965228  0.100990

In [15]:
pd.concat([df1,df2],ignore_index=True) #add new index

A         B         C         E         F
0 -0.527470 -0.611288  0.609666       NaN       NaN
1 -1.330374 -1.282318 -1.551537       NaN       NaN
2 -1.098868  0.456488  0.352204       NaN       NaN
3  1.786392  0.991445 -0.485267       NaN       NaN
4       NaN       NaN -1.692135  0.176689 -0.327256
5       NaN       NaN  0.351587  0.015693  0.887437
6       NaN       NaN  1.467077 -0.987346 -1.587642
7       NaN       NaN  0.999575 -0.965228  0.100990