## Notas numpy

In [4]:
#La forma estándar de importar NumPy
import numpy as np

In [15]:
lista1 = [12,43,52,78] 

#Convertir una lista en un arreglo unidimensional
arreglo1d = np.array(list1)

arreglo1d

array([12, 43, 52])

In [17]:
lista2 = [24,43,54,65]

lista2d = [lista1,lista2]

#Arreglo multidimensional 2d
arreglo2d = np.array(lista2d)

arreglo2d

array([[12, 43, 52, 78],
       [24, 43, 54, 65]])

In [ ]:
#Información básica

In [18]:
#Dimensiones del arreglo.
arreglo2d.shape

(2, 4)

In [19]:
#Tipo del arreglo
arreglo2d.dtype

dtype('int64')

In [21]:
#Cantidad de elementos del arreglo
arreglo2d.size

8

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###Creación de un arreglo

In [25]:
#Desde una lista y dando el tipo 
lista_complejos = [[1,2,3],[4,5,6]]

arreglo_complejo = np.array(lista_complejos, dtype=complex)

arreglo_complejo

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [29]:
#Desde un rango de números conocidos

arreglo_rango_pares = np.arange(0,30,2)

In [31]:
#Arrelo de ceros

arreglo_ceros = np.zeros(9)
arreglo_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
#Arrelo de unos

arreglo_unos = np.ones(9)
arreglo_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
#Arrelo ojo

arreglo_ojo = np.eye(3)
arreglo_ojo

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])